/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   condition-operator-dropdown.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare namespace UiElements {

  /**
   * Variable editor allows to edit variables in actions editor.
   *
   * ### Styling
   *
   * `<condition-operator-dropdown>` provides the following custom properties and
   * mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--condition-operator-dropdown` | Mixin applied to the element | `{}`
   * `--condition-operator-dropdown-background-color` | Background color of the
   * editor | `rgba(0, 162, 223, 0.05)`
   */
  class ConditionOperatorDropdown extends
    Polymer.IronFormElementBehavior(
    Object) {

    /**
     * Renders the editor in read only mode
     */
    readonly: boolean|null|undefined;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "condition-operator-dropdown": UiElements.ConditionOperatorDropdown;
  }
}

export {};
