/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ActionBase.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html} from 'lit-element';

export {ActionBase};

declare class ActionBase extends LitElement {
  constructor();

  /**
   * Sets path info variables when action's source change.
   *
   * @param source Current source of the action.
   */
  _processSource(source: String|null): void;
  _computeSourcePath(): void;
  _propertyName(name: any): any;
  _propertyInputChanged(e: any): void;
  _propertyEnabledHandler(e: any): void;
  _propertySelectionHandler(e: any): void;
  _notifyChangeProperty(): void;

  /**
   * Dispatches the `remove` custom event so the panel can remove
   * the item from the list.
   */
  remove(): void;
  _sourceTypeTemplate(): any;
  _sourceTemplate(): any;
  _pathTemplate(): any;
  _removeTemplate(): any;
  _propertySwitchTemplate(): any;
}
