/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/ConditionOperatorDropdown.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

export {ConditionOperatorDropdown};

declare namespace UiElements {

  /**
   * Variable editor allows to edit variables in actions editor.
   *
   * ### Styling
   *
   * `<condition-operator-dropdown>` provides the following custom properties and
   * mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--condition-operator-dropdown` | Mixin applied to the element | `{}`
   * `--condition-operator-dropdown-background-color` | Background color of the
   * editor | `rgba(0, 162, 223, 0.05)`
   */
  class ConditionOperatorDropdown extends LitElement {

    /**
     * Renders the editor in read only mode
     */
    readOnly: boolean|null|undefined;

    /**
     * Operator value
     */
    value: string|null|undefined;

    /**
     * Name of the control
     */
    name: string|null|undefined;

    /**
     * Enables compatibility with Anypoint platform
     */
    compatibility: boolean|null|undefined;

    /**
     * Enables Material Design Outlined inputs
     */
    outlined: boolean|null|undefined;
    constructor();
    render(): any;
    _selectionHandler(e: any): void;
  }
}
