/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/RequestVariableEditor.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {ActionBase} from './ActionBase.js';

import {html, css} from 'lit-element';

export {RequestVariableEditor};

declare namespace UiElements {

  /**
   * Variable editor allows to edit variables in actions editor.
   *
   * ### Styling
   *
   * `<request-variable-editor>` provides the following custom properties and
   * mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--request-variable-editor` | Mixin applied to the element | `{}`
   */
  class RequestVariableEditor extends ActionBase {

    /**
     * Definied action.
     */
    action: object|null|undefined;

    /**
     * List of variables sugesstions to display in the combo box.
     */
    variablesSuggestions: any[]|null|undefined;
    constructor();
    render(): any;
  }
}
